{% set prefix = "spacy-model-" %}
{% set lang = "nl" %}
{% set name = lang + "_core_news" %}
{% set version = "3.4.0" %}

package:
  name: {{ prefix }}{{ lang|lower }}
  version: {{ version }}

source:
  - folder: sm
    url: https://github.com/explosion/spacy-models/releases/download/{{ name }}_sm-{{ version }}/{{ name }}_sm-{{ version }}.tar.gz
    sha256: 7672f0e48874360c5835c0675efea5ddbca3f688ce200fcf210c97fd164af964
  - folder: md
    url: https://github.com/explosion/spacy-models/releases/download/{{ name }}_md-{{ version }}/{{ name }}_md-{{ version }}.tar.gz
    sha256: 3ba178a0d2198b4923c8991aa6d336ae0ea80a7e45a58dcec496ac7ae562ae5f
  - folder: lg
    url: https://github.com/explosion/spacy-models/releases/download/{{ name }}_lg-{{ version }}/{{ name }}_lg-{{ version }}.tar.gz
    sha256: 20eb757fcaecb5aafe6fde19504604247c8ee532f751f48917ec90cc110ee1c0

build:
  number: 0

test:
  commands:
    - echo "make lint happy"

outputs:
  - name: {{ prefix }}{{ name }}_{{ size }}
    script: build.sh  # [unix]
    script: build.bat  # [win]
    requirements:
      host:
        - python
        - pip
      run:
        - python
        - setuptools
    test:
      imports:
        - {{ name }}_{{ size }}
      requires:
        - spacy {{ version.split('.')[0] }}.*
      commands:
        - python -c "import {{ name }}_{{ size }} as m; m.load()"
        - python -c "import spacy; spacy.load('{{ name }}_{{ size }}')"

about:
  home: https://spacy.io
  license: CC-BY-SA-4.0
  summary: Dutch multi-task CNN trained on the Universal Dependencies and WikiNER corpus.
  license_file: LICENSE
  doc_url: https://spacy.io/models/nl

extra:
  recipe-maintainers:
    - FernandezMathieu
    - JIVJGFJZKF
    - JennaLipscomb
    - mxr-conda
